apiVersion: argoproj.io/v1alpha1 
kind: Application
metadata: 
  name: myapp-argo-application
  namespace: argocd

spec: 
  project: defult
  
  source:
    repoUrl: https://github.com/adarshadhal/argocd.git
    targetRevision: HEAD
    path: myapp

  destination:
    server: https://kubernetes.defult.svc
    namespace: myapp
  
  synPolicy:
    synOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

